/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assignment.assignment5009cem;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;



/**
 *
 * @author User
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        label_loginTitle.setFont(new Font("Serif", Font.BOLD, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_userID = new javax.swing.JLabel();
        label_passwordTitle = new javax.swing.JLabel();
        textField_userID = new javax.swing.JTextField();
        textField_password = new javax.swing.JTextField();
        button_login = new javax.swing.JButton();
        button_companyRegister = new javax.swing.JButton();
        label_loginTitle = new javax.swing.JLabel();
        label_companyRegisterTitle = new javax.swing.JLabel();
        label_userRegisterTitle = new javax.swing.JLabel();
        button_userRegister = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        comboBox_userType = new javax.swing.JComboBox<>();
        label_logInAsTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 251, 235));

        label_userID.setText("User ID: ");

        label_passwordTitle.setText("Password:");

        button_login.setBackground(new java.awt.Color(64, 50, 184));
        button_login.setForeground(new java.awt.Color(255, 255, 255));
        button_login.setText("Login");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        button_companyRegister.setBackground(new java.awt.Color(64, 50, 184));
        button_companyRegister.setForeground(new java.awt.Color(255, 255, 255));
        button_companyRegister.setText("Go Register");
        button_companyRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_companyRegisterActionPerformed(evt);
            }
        });

        label_loginTitle.setForeground(new java.awt.Color(64, 50, 184));
        label_loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_loginTitle.setText("LOGIN");

        label_companyRegisterTitle.setText("Register as a Company: ");

        label_userRegisterTitle.setText("Register as a User:");

        button_userRegister.setBackground(new java.awt.Color(64, 50, 184));
        button_userRegister.setForeground(new java.awt.Color(255, 255, 255));
        button_userRegister.setText("Go Register");
        button_userRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_userRegisterActionPerformed(evt);
            }
        });

        comboBox_userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Provider" }));

        label_logInAsTitle.setText("Log In As:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_loginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_userRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_userRegister))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_companyRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_companyRegister)
                                .addGap(464, 464, 464))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_login)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_logInAsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(label_userID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_passwordTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textField_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField_userID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBox_userType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator1)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(label_loginTitle)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_userType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_logInAsTitle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_userID)
                    .addComponent(textField_userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_passwordTitle)
                    .addComponent(textField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_companyRegisterTitle)
                    .addComponent(button_companyRegister)
                    .addComponent(label_userRegisterTitle)
                    .addComponent(button_userRegister))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(496, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(101, 101, 101)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //this button is responsible for brining the company over to the registration page
    private void button_companyRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_companyRegisterActionPerformed
        RegisterUI itemloader = new RegisterUI();
        itemloader.setVisible(true);
        dispose();  //dispose the login page and only show the register page
    }//GEN-LAST:event_button_companyRegisterActionPerformed

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        String userType = comboBox_userType.getSelectedItem().toString();  //we allow user to select their role such as "as a user" or "as a company"
        
        
        //check what user is loggin in. Either normal user or a provvider which whom are the company or admin
        if(userType.equals("User")){
            String userID = "";
            String password = "";
            boolean loginStatus = false;
            
            try{
                userID = textField_userID.getText();
                password = textField_password.getText();
            }
            catch(NumberFormatException e){
                System.out.println(e);
            }
            
            try{
                    Connection conDB = DriverManager.getConnection("jdbc:mysql://localhost/oecd","root","");  //db connection

                    String query = "SELECT * from users Where userID = '" + userID + "'";  //sql query
                    Statement stmt = conDB.createStatement();  
                    ResultSet rs = stmt.executeQuery(query);
                    
                    //check against user after reading it from the database
                    while(rs.next()){
                        //if correct id and password, will go into here can change the login state to true
                        if(textField_userID.getText().equals(rs.getString("userID")) && password.equals(rs.getString("password"))){
                            loginStatus = true;
                            
                            //once the credentials is true set the entire company class to make sure the data is ready to be use
                            Users userEntity = Users.getInstance();
                            userEntity.setUserID(userID);
                            userEntity.setUserName(rs.getString("userName"));
                            userEntity.setEmail(rs.getString("email"));
                            userEntity.setContactNumber(rs.getString("contactNumber"));
                        }
                    }

            }
            catch(SQLException exception){  //catch any sql/db error

                System.out.println(exception);
                
            }
            
            //if state is true then wil direct to dashboard
            if(loginStatus == true){
                UserDashboardUI itemloader = new UserDashboardUI();
                itemloader.setVisible(true);
                dispose();
            }
            else{
                label_loginTitle.setText("Wrong Credentials. Check your User ID and Password");
            }
            
        }
        else if(userType.equals("Provider")){
            
            //declaration and initialization 
            String userID = "";
            String password="";
            boolean loginStatus = false;  //the login state. True is go, false is no go. Default at false
            
            //to catch the error when user input nothing and press login.
            try{
                userID  = textField_userID.getText();
                password = textField_password.getText();
            }
            catch(NumberFormatException e){
                System.out.println(e);
            }
            

            if(userID.substring(0,1).equals("A")){
                
                try{
                    Connection conDB = DriverManager.getConnection("jdbc:mysql://localhost/oecd","root","");  //db connection

                    String query = "SELECT * from admin Where adminID = '" + userID + "'";  //sql query
                    Statement stmt = conDB.createStatement();  
                    ResultSet rs = stmt.executeQuery(query);
                    
                    //check against user after reading it from the database
                    while(rs.next()){
                        //if correct id and password, will go into here can change the login state to true
                        if(textField_userID.getText().equals(rs.getString("adminID")) && password.equals(rs.getString("adminPassword"))){
                            loginStatus = true;
                            
                        }
                    }

                }
                catch(SQLException exception){  //catch any sql/db error

                    System.out.println(exception);

                }
                
                if(loginStatus == true){
                    AdminDashboardUI itemloader = new AdminDashboardUI();
                    itemloader.setVisible(true);
                    dispose();
                }
                else{
                    label_loginTitle.setText("Wrong Credentials. Check your User ID and Password");
                }
                
            }
            else{
                
                long userIDlong  = (Long.parseLong(textField_userID.getText()));
                //connecting to db and get the data necessary and check against user input
                try{
                        Connection conDB = DriverManager.getConnection("jdbc:mysql://localhost/oecd","root","");  //db connection

                        String query = "SELECT * from company Where companyID = '" + userIDlong + "'";  //sql query
                        Statement stmt = conDB.createStatement();  
                        ResultSet rs = stmt.executeQuery(query);

                        //check against user after reading it from the database
                        while(rs.next()){
                            //if correct id and password, will go into here can change the login state to true
                            if(textField_userID.getText().equals(rs.getString("companyID")) && password.equals(rs.getString("password"))){
                                loginStatus = true;

                                //once the credentials is true set the entire company class to make sure the data is ready to be use
                                Company companyEntity = Company.getInstance();
                                companyEntity.setCompanyID(userIDlong);
                                companyEntity.setCompanyName(rs.getString("companyName"));
                                companyEntity.setCompanyAddress(rs.getString("companyAddress"));
                                companyEntity.setPostalCode(Integer.parseInt(rs.getString("postalCode")));
                                companyEntity.setStatus("status");
                                companyEntity.setContactNumber(rs.getString("contactNumber"));
                                companyEntity.setSubscriptionDate(rs.getString("subscriptionDate"));
                                companyEntity.setSubscriptionDuration(rs.getString("subscriptionDuration"));
                            }
                        }

                }
                catch(SQLException exception){  //catch any sql/db error

                    System.out.println(exception);

                }

                //if state is true then wil direct to dashboard
                if(loginStatus == true){
                    CompanyDashboardUI itemloader = new CompanyDashboardUI();
                    itemloader.setVisible(true);
                    dispose();
                }
                else{
                    label_loginTitle.setText("Wrong Credentials. Check your User ID and Password");
                }
            }
        }
    }//GEN-LAST:event_button_loginActionPerformed

    private void button_userRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_userRegisterActionPerformed

        UserRegisterUI itemloader = new UserRegisterUI();
        itemloader.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_userRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginUI().setVisible(true);
                                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton button_companyRegister;
    private static javax.swing.JButton button_login;
    private javax.swing.JButton button_userRegister;
    private javax.swing.JComboBox<String> comboBox_userType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_companyRegisterTitle;
    private javax.swing.JLabel label_logInAsTitle;
    private static javax.swing.JLabel label_loginTitle;
    private static javax.swing.JLabel label_passwordTitle;
    private static javax.swing.JLabel label_userID;
    private javax.swing.JLabel label_userRegisterTitle;
    private static javax.swing.JTextField textField_password;
    private static javax.swing.JTextField textField_userID;
    // End of variables declaration//GEN-END:variables
}
