/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assignment.assignment5009cem;

import java.awt.Font;

/**
 *
 * @author User
 */
public class SubscriptionUI extends javax.swing.JFrame {

    /**
     * Creates new form subscriptionFees
     */
    public SubscriptionUI() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);  
        label_subscriptionPaymentTitle.setFont(new Font("Serif", Font.BOLD, 20));
        label_durationTitle.setFont(new Font("Serif", Font.PLAIN, 14));
        label_paymentDetailsTitle.setFont(new Font("Serif", Font.BOLD, 16));
        label_nameOnCardTitle.setFont(new Font("Serif", Font.PLAIN, 14));
        label_cardNumberTitle.setFont(new Font("Serif", Font.PLAIN, 14));
        label_expirationDateTitle.setFont(new Font("Serif", Font.PLAIN, 14));
        label_cvcTitle.setFont(new Font("Serif", Font.PLAIN, 14));
        jRadioButton1.setFont(new Font("Serif", Font.PLAIN, 14));
        jRadioButton2.setFont(new Font("Serif", Font.PLAIN, 14));
        textField_nameOnCard.setFont(new Font("Serif", Font.PLAIN, 14));
        textField_expirationDate.setFont(new Font("Serif", Font.PLAIN, 14));
        textField_cardNumber.setFont(new Font("Serif", Font.PLAIN, 14));
        textField_cvc.setFont(new Font("Serif", Font.PLAIN, 14));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrp_subscriptionDuration = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        button_next = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        label_durationTitle = new javax.swing.JLabel();
        label_paymentDetailsTitle = new javax.swing.JLabel();
        label_nameOnCardTitle = new javax.swing.JLabel();
        textField_nameOnCard = new javax.swing.JTextField();
        label_cardNumberTitle = new javax.swing.JLabel();
        textField_cardNumber = new javax.swing.JTextField();
        label_expirationDateTitle = new javax.swing.JLabel();
        textField_expirationDate = new javax.swing.JTextField();
        label_cvcTitle = new javax.swing.JLabel();
        textField_cvc = new javax.swing.JTextField();
        label_subscriptionPaymentTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 251, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        button_next.setBackground(new java.awt.Color(64, 50, 184));
        button_next.setForeground(new java.awt.Color(255, 255, 255));
        button_next.setText("Next >");
        button_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nextActionPerformed(evt);
            }
        });

        buttonGrp_subscriptionDuration.add(jRadioButton1);
        jRadioButton1.setText("One Year ( RM599.00 )");
        jRadioButton1.setActionCommand("1 Year");

        buttonGrp_subscriptionDuration.add(jRadioButton2);
        jRadioButton2.setText("Three Years ( RM1599.00 )");
        jRadioButton2.setActionCommand("3 Years");

        label_durationTitle.setText("Duration to Subscribe : ");

        label_paymentDetailsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_paymentDetailsTitle.setText("Payment Details :");

        label_nameOnCardTitle.setText("Name on card :");

        label_cardNumberTitle.setText("Card number :");

        label_expirationDateTitle.setText("Expiration Number :");

        label_cvcTitle.setText("CVC Code :");

        label_subscriptionPaymentTitle.setForeground(new java.awt.Color(64, 50, 184));
        label_subscriptionPaymentTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_subscriptionPaymentTitle.setText("Payment for Subscription");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 218, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_nameOnCardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_cardNumberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_expirationDateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_cvcTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textField_cvc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField_expirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField_cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField_nameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(286, 286, 286))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(button_next, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(420, 420, 420))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label_durationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(207, 207, 207))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_subscriptionPaymentTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_paymentDetailsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(label_subscriptionPaymentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(label_durationTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addGap(37, 37, 37)
                .addComponent(label_paymentDetailsTitle)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nameOnCardTitle)
                    .addComponent(textField_nameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cardNumberTitle))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_expirationDateTitle)
                    .addComponent(textField_expirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cvcTitle)
                    .addComponent(textField_cvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_next, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nextActionPerformed
        
        //call the singleton company object to continue store the subscription data
        Company companyEntity = Company.getInstance();                
        companyEntity.setSubscriptionDuration(buttonGrp_subscriptionDuration.getSelection().getActionCommand()); //to get what subscription plan they selected
        companyEntity.setStatus("Pending");  //the status of all new user are set to pending
        
        //go next step of the registration process
        ServicesUI itemloader = new ServicesUI();
        itemloader.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubscriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubscriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubscriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubscriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubscriptionUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGrp_subscriptionDuration;
    private static javax.swing.JButton button_next;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JRadioButton jRadioButton1;
    private static javax.swing.JRadioButton jRadioButton2;
    private static javax.swing.JLabel label_cardNumberTitle;
    private static javax.swing.JLabel label_cvcTitle;
    private static javax.swing.JLabel label_durationTitle;
    private static javax.swing.JLabel label_expirationDateTitle;
    private static javax.swing.JLabel label_nameOnCardTitle;
    private static javax.swing.JLabel label_paymentDetailsTitle;
    private static javax.swing.JLabel label_subscriptionPaymentTitle;
    private static javax.swing.JTextField textField_cardNumber;
    private static javax.swing.JTextField textField_cvc;
    private static javax.swing.JTextField textField_expirationDate;
    private static javax.swing.JTextField textField_nameOnCard;
    // End of variables declaration//GEN-END:variables
}
