/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assignment.assignment5009cem;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class UserDashboardUI extends javax.swing.JFrame {
    
    long providerID_ready = 0;
    String serviceType_ready = "";
    int requestID = 0;
    
    /**
     * Creates new form UserDashboardUI
     */
    public UserDashboardUI() {
        initComponents();
        jLayeredPane1.setVisible(false);
        getContentPane().setBackground(new java.awt.Color(255, 251,235));
        this.pack();
        this.setLocationRelativeTo(null);
        label_userDashboardTitle.setFont(new Font("Serif", Font.BOLD, 20));
        label_companyListTitle.setFont(new Font("Serif", Font.BOLD, 20));
        label_helpRequestTitle.setFont(new Font("Serif", Font.BOLD,20));
        label_myRequestTitle.setFont(new Font("Serif", Font.BOLD,20));
        label_profileTitle.setFont(new Font("Serif",Font.BOLD,20));
        label_areYouSureTitle.setFont(new Font("Serif",Font.BOLD,20));
        label_completeRequestTitle.setFont(new Font("Serif",Font.BOLD,20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdialog_requestConfirmation = new javax.swing.JDialog();
        label_areYouSureTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button_confirm = new javax.swing.JButton();
        textField_address = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        textArea_description = new javax.swing.JTextArea();
        label_adddressTitle = new javax.swing.JLabel();
        label_descriptionTitle = new javax.swing.JLabel();
        button_cancel = new javax.swing.JButton();
        jdialog_completeRequest = new javax.swing.JDialog();
        label_completeRequestTitle = new javax.swing.JLabel();
        button_Done = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textArea_feedback = new javax.swing.JTextArea();
        label_feedbackTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_userDashboardTitle = new javax.swing.JLabel();
        button_viewCompanyList = new javax.swing.JButton();
        button_RequestHelp = new javax.swing.JButton();
        button_viewMyRequest = new javax.swing.JButton();
        button_profile = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        label_companyListTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_companyList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        label_helpRequestTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_helpRequest = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        label_myRequestTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_myRequest = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        label_profileTitle = new javax.swing.JLabel();
        label_idTitle = new javax.swing.JLabel();
        label_nameTitle = new javax.swing.JLabel();
        label_emailTitle = new javax.swing.JLabel();
        label_contactTitle = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_contact = new javax.swing.JLabel();

        jdialog_requestConfirmation.setSize(new java.awt.Dimension(540, 400));

        label_areYouSureTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_areYouSureTitle.setText("Are you sure you want to place this Help Request ?");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fill In The Necessary Details");

        button_confirm.setText("Confirm");
        button_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_confirmActionPerformed(evt);
            }
        });

        textArea_description.setColumns(20);
        textArea_description.setRows(5);
        jScrollPane4.setViewportView(textArea_description);

        label_adddressTitle.setText("Address: ");

        label_descriptionTitle.setText("Description:");

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdialog_requestConfirmationLayout = new javax.swing.GroupLayout(jdialog_requestConfirmation.getContentPane());
        jdialog_requestConfirmation.getContentPane().setLayout(jdialog_requestConfirmationLayout);
        jdialog_requestConfirmationLayout.setHorizontalGroup(
            jdialog_requestConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdialog_requestConfirmationLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jdialog_requestConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdialog_requestConfirmationLayout.createSequentialGroup()
                        .addComponent(label_areYouSureTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(jdialog_requestConfirmationLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jdialog_requestConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdialog_requestConfirmationLayout.createSequentialGroup()
                        .addGroup(jdialog_requestConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdialog_requestConfirmationLayout.createSequentialGroup()
                                .addComponent(label_adddressTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdialog_requestConfirmationLayout.createSequentialGroup()
                                .addComponent(label_descriptionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jdialog_requestConfirmationLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(button_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        jdialog_requestConfirmationLayout.setVerticalGroup(
            jdialog_requestConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdialog_requestConfirmationLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label_areYouSureTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(jdialog_requestConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_adddressTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdialog_requestConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_descriptionTitle)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jdialog_requestConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_confirm)
                    .addComponent(button_cancel))
                .addGap(50, 50, 50))
        );

        jdialog_completeRequest.setSize(new java.awt.Dimension(540, 400));

        label_completeRequestTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_completeRequestTitle.setText("Complete Request?");

        button_Done.setText("Done");
        button_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DoneActionPerformed(evt);
            }
        });

        textArea_feedback.setColumns(20);
        textArea_feedback.setRows(5);
        jScrollPane5.setViewportView(textArea_feedback);

        label_feedbackTitle.setText("Feedback");

        javax.swing.GroupLayout jdialog_completeRequestLayout = new javax.swing.GroupLayout(jdialog_completeRequest.getContentPane());
        jdialog_completeRequest.getContentPane().setLayout(jdialog_completeRequestLayout);
        jdialog_completeRequestLayout.setHorizontalGroup(
            jdialog_completeRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdialog_completeRequestLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(label_feedbackTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdialog_completeRequestLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jdialog_completeRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdialog_completeRequestLayout.createSequentialGroup()
                        .addComponent(label_completeRequestTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdialog_completeRequestLayout.createSequentialGroup()
                        .addComponent(button_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))))
        );
        jdialog_completeRequestLayout.setVerticalGroup(
            jdialog_completeRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdialog_completeRequestLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label_completeRequestTitle)
                .addGap(49, 49, 49)
                .addGroup(jdialog_completeRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_feedbackTitle)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(button_Done)
                .addGap(61, 61, 61))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 251, 235));

        label_userDashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_userDashboardTitle.setText("User Dashboard");

        button_viewCompanyList.setText("View Company");
        button_viewCompanyList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewCompanyListActionPerformed(evt);
            }
        });

        button_RequestHelp.setText("Request Help");
        button_RequestHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RequestHelpActionPerformed(evt);
            }
        });

        button_viewMyRequest.setText("My Request");
        button_viewMyRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewMyRequestActionPerformed(evt);
            }
        });

        button_profile.setText("View Profile");
        button_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_userDashboardTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(button_viewCompanyList)
                .addGap(92, 92, 92)
                .addComponent(button_RequestHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(button_viewMyRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(button_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(label_userDashboardTitle)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_viewCompanyList)
                    .addComponent(button_RequestHelp)
                    .addComponent(button_viewMyRequest)
                    .addComponent(button_profile))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 190));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 251, 235));

        label_companyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_companyListTitle.setText("Company List");

        table_companyList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Address", "Postal Code", "Comtact Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_companyList);
        if (table_companyList.getColumnModel().getColumnCount() > 0) {
            table_companyList.getColumnModel().getColumn(0).setResizable(false);
            table_companyList.getColumnModel().getColumn(1).setResizable(false);
            table_companyList.getColumnModel().getColumn(2).setResizable(false);
            table_companyList.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_companyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label_companyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(255, 251, 235));

        label_helpRequestTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_helpRequestTitle.setText("Help Request");

        table_helpRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Provider  ID", "Provider Name", "Service Type", "Service Description", "Postal Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_helpRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_helpRequestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_helpRequest);
        if (table_helpRequest.getColumnModel().getColumnCount() > 0) {
            table_helpRequest.getColumnModel().getColumn(0).setResizable(false);
            table_helpRequest.getColumnModel().getColumn(1).setResizable(false);
            table_helpRequest.getColumnModel().getColumn(2).setResizable(false);
            table_helpRequest.getColumnModel().getColumn(3).setResizable(false);
            table_helpRequest.getColumnModel().getColumn(4).setResizable(false);
            table_helpRequest.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addComponent(label_helpRequestTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_helpRequestTitle)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.add(jPanel3, "card3");

        jPanel4.setBackground(new java.awt.Color(255, 251, 235));

        label_myRequestTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_myRequestTitle.setText("My Request");

        table_myRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Provider ID", "Service Type", "Description", "Location", "Status", "Comment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_myRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_myRequestMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_myRequest);
        if (table_myRequest.getColumnModel().getColumnCount() > 0) {
            table_myRequest.getColumnModel().getColumn(0).setResizable(false);
            table_myRequest.getColumnModel().getColumn(1).setResizable(false);
            table_myRequest.getColumnModel().getColumn(2).setResizable(false);
            table_myRequest.getColumnModel().getColumn(3).setResizable(false);
            table_myRequest.getColumnModel().getColumn(4).setResizable(false);
            table_myRequest.getColumnModel().getColumn(5).setResizable(false);
            table_myRequest.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addComponent(label_myRequestTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_myRequestTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.add(jPanel4, "card4");

        jPanel5.setBackground(new java.awt.Color(255, 251, 235));

        label_profileTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_profileTitle.setText("Profile");

        label_idTitle.setText("User ID: ");

        label_nameTitle.setText("User Name:");

        label_emailTitle.setText("Email");

        label_contactTitle.setText("Contact Number");

        label_contact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_profileTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_nameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_idTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_emailTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_contactTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(272, 272, 272))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(label_profileTitle)
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(label_idTitle))
                            .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(label_nameTitle))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_emailTitle)
                    .addComponent(label_email, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_contactTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel5, "card5");

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1000, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_viewCompanyListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewCompanyListActionPerformed
        
        Connection conDB = null;
        String name = "";
        String address = "";
        int postalCode = 0;
        String contactNumber = "";
        
        
        try{
            
            conDB = DriverManager.getConnection("jdbc:mysql://localhost/oecd","root","");
            Statement stmt = conDB.createStatement();
            
            //code for read operation
            String query = "SELECT * from company WHERE status = '" +"Approved"+ "'";
            ResultSet rs = stmt.executeQuery(query);
            
            DefaultTableModel model = (DefaultTableModel) table_companyList.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                name = (rs.getString("companyName"));
                address =(rs.getString("companyAddress"));
                postalCode = (Integer.parseInt(rs.getString("postalCode")));
                contactNumber = (rs.getString("contactNumber"));
                
                Object[] row = {name,address,postalCode,contactNumber};
                model.addRow(row);
                
            }
        }
        catch(SQLException exception){
            
            System.out.print(exception.getMessage());
        }
        
        jLayeredPane1.setVisible(true);
        switchPanel(jPanel2);  //each button use this function to swtich the layered panel by passing in which panel
    }//GEN-LAST:event_button_viewCompanyListActionPerformed

    private void button_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profileActionPerformed
        Users userEntity = Users.getInstance();
        
        label_id.setText(userEntity.getUserID());
        label_name.setText(userEntity.getUserName());
        label_email.setText(userEntity.getEmail());
        label_contact.setText(userEntity.getContactNumber());
        
        jLayeredPane1.setVisible(true);
        switchPanel(jPanel5);
    }//GEN-LAST:event_button_profileActionPerformed

    private void button_RequestHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RequestHelpActionPerformed
        
        Connection conDB = null;
        int id = 0;
        long providerID = 0;
        String providerName = "";
        String serviceType = "";
        String description = "";
        int postalCode = 0;
        
        
        try{
            conDB = DriverManager.getConnection("jdbc:mysql://localhost/oecd","root","");
            Statement stmt = conDB.createStatement();
            
            //code for read operation
            String query = "SELECT * from services WHERE status = '" +"Approved"+ "'";
            ResultSet rs = stmt.executeQuery(query);
            
            DefaultTableModel model = (DefaultTableModel) table_helpRequest.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                id = (Integer.parseInt(rs.getString("serviceID")));
                providerID =(Long.parseLong(rs.getString("providerID")));
                providerName = (rs.getString("providerName"));
                serviceType = (rs.getString("serviceType"));
                description = (rs.getString("serviceDescription"));
                postalCode = (Integer.parseInt(rs.getString("postalCode")));
                
                Object[] row = {id,providerID,providerName,serviceType,description,postalCode};
                model.addRow(row);
                
            }
        }
        catch(SQLException exception){
            
            System.out.print(exception.getMessage());
        }
        
        jLayeredPane1.setVisible(true);
        switchPanel(jPanel3);
    }//GEN-LAST:event_button_RequestHelpActionPerformed

    private void button_viewMyRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewMyRequestActionPerformed
        
        Connection conDB = null;
        int id = 0;
        long providerID = 0;
        String serviceType = "";
        String description = "";
        String location = "";
        String status = "";
        String feedback = "";
        
        Users userEntity = Users.getInstance();
        
        try{
            conDB = DriverManager.getConnection("jdbc:mysql://localhost/oecd","root","");
            Statement stmt = conDB.createStatement();
            
            //code for read operation
            String query = "SELECT * from request WHERE userID = '" +userEntity.getUserID()+ "'";
            ResultSet rs = stmt.executeQuery(query);
            
            DefaultTableModel model = (DefaultTableModel) table_myRequest.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                
                id = (Integer.parseInt(rs.getString("requestID")));
                providerID =(Long.parseLong(rs.getString("providerID")));
                serviceType = rs.getString("serviceType");
                description = rs.getString("description");
                location = rs.getString("location");
                status = rs.getString("status");
                feedback = rs.getString("feedback");
                
                Object[] row = {id,providerID,serviceType,description,location,status,feedback};
                model.addRow(row);
                
            }
        }
        catch(SQLException exception){
            
            System.out.print(exception.getMessage());
        }
        
        
        jLayeredPane1.setVisible(true);
        switchPanel(jPanel4);
    }//GEN-LAST:event_button_viewMyRequestActionPerformed

    private void table_helpRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_helpRequestMouseClicked
                
        int index = table_helpRequest.getSelectedRow();
        TableModel model = table_helpRequest.getModel();
        
        providerID_ready = (Long.parseLong(model.getValueAt(index, 1).toString()));
        serviceType_ready = model.getValueAt(index, 3).toString();

        jdialog_requestConfirmation.setVisible(true);
        jdialog_requestConfirmation.pack();
        jdialog_requestConfirmation.setLocationRelativeTo(null);

    }//GEN-LAST:event_table_helpRequestMouseClicked

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed

        jdialog_requestConfirmation.dispose();

    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_confirmActionPerformed

        Connection conDB = null;

        Users userEntity = Users.getInstance();
        String description = textArea_description.getText();
        String location = textField_address.getText();
        String feedback ="";

        try{
            conDB = DriverManager.getConnection("jdbc:mysql://localhost/oecd","root","");
            Statement stmt = conDB.createStatement();

            //code for insert operation
            
            if(serviceType_ready.equals("Police") || serviceType_ready.equals("Hospital")){
                stmt.executeUpdate("INSERT INTO request (userID, userName,providerID,serviceType,description,status,location,feedback) "
                + "VALUES ('"+userEntity.getUserID()+"','"+userEntity.getUserName()+"','"+providerID_ready+"',"
                + "'"+serviceType_ready+"','"+description+"','"+"ON THE WAY"+"','"+location+"','"+feedback+"')");
            }else{
                stmt.executeUpdate("INSERT INTO request (userID, userName,providerID,serviceType,description,status,location,feedback) "
                + "VALUES ('"+userEntity.getUserID()+"','"+userEntity.getUserName()+"','"+providerID_ready+"',"
                + "'"+serviceType_ready+"','"+description+"','"+"Pending"+"','"+location+"','"+feedback+"')");
            }
            
            
        }
        catch(SQLException exception){

            System.out.print(exception.getMessage());
        }
        
        jdialog_requestConfirmation.dispose();
    }//GEN-LAST:event_button_confirmActionPerformed

    private void table_myRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_myRequestMouseClicked

        
        int index = table_myRequest.getSelectedRow();
        TableModel model = table_myRequest.getModel();
        
        requestID = (Integer.parseInt(model.getValueAt(index, 0).toString()));
        
        
        if(model.getValueAt(index, 5).toString().equals("Accepted")){
            jdialog_completeRequest.setVisible(true);
            jdialog_completeRequest.pack();
            jdialog_completeRequest.setLocationRelativeTo(null);
        }

    }//GEN-LAST:event_table_myRequestMouseClicked

    private void button_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DoneActionPerformed
        
        Connection conDB = null;
        
        String feedback = textArea_feedback.getText();
        String newStatus = "Done";

        try{
            conDB = DriverManager.getConnection("jdbc:mysql://localhost/oecd","root","");
            Statement stmt = conDB.createStatement();
            Statement stmt2 = conDB.createStatement();

            //code for insert operation
            stmt.executeUpdate("update request set feedback = '"+feedback+"' where requestID = '"+requestID+"'");
            
            stmt2.executeUpdate("update request set status = '"+newStatus+"' where requestID = '"+requestID+"'");
        }
        catch(SQLException exception){

            System.out.print(exception.getMessage());
        }
        
        jdialog_completeRequest.dispose();

    }//GEN-LAST:event_button_DoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboardUI().setVisible(true);
            }
        });
    }
   
    //switch panel function is to switch the layered panels in the UI when button is click
    public void switchPanel(JPanel panel){
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Done;
    private javax.swing.JButton button_RequestHelp;
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_confirm;
    private javax.swing.JButton button_profile;
    private javax.swing.JButton button_viewCompanyList;
    private javax.swing.JButton button_viewMyRequest;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog jdialog_completeRequest;
    private javax.swing.JDialog jdialog_requestConfirmation;
    private javax.swing.JLabel label_adddressTitle;
    private javax.swing.JLabel label_areYouSureTitle;
    private javax.swing.JLabel label_companyListTitle;
    private javax.swing.JLabel label_completeRequestTitle;
    private javax.swing.JLabel label_contact;
    private javax.swing.JLabel label_contactTitle;
    private javax.swing.JLabel label_descriptionTitle;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_emailTitle;
    private javax.swing.JLabel label_feedbackTitle;
    private javax.swing.JLabel label_helpRequestTitle;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_idTitle;
    private javax.swing.JLabel label_myRequestTitle;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_nameTitle;
    private javax.swing.JLabel label_profileTitle;
    private javax.swing.JLabel label_userDashboardTitle;
    private javax.swing.JTable table_companyList;
    private javax.swing.JTable table_helpRequest;
    private javax.swing.JTable table_myRequest;
    private javax.swing.JTextArea textArea_description;
    private javax.swing.JTextArea textArea_feedback;
    private javax.swing.JTextField textField_address;
    // End of variables declaration//GEN-END:variables
}
