/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assignment.assignment5009cem;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author user
 */
public class UserRegisterUI extends javax.swing.JFrame {

    /**
     * Creates new form UserRegisterUI
     */
    public UserRegisterUI() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        label_registerTitle.setFont(new Font("Serif", Font.BOLD, 20));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdialog_registerComplete = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button_done = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label_registerTitle = new javax.swing.JLabel();
        label_ICNumberTitle = new javax.swing.JLabel();
        label_userNameTitle = new javax.swing.JLabel();
        label_passwordTitle = new javax.swing.JLabel();
        label_emailTitle = new javax.swing.JLabel();
        label_contactNumberTitle = new javax.swing.JLabel();
        textfield_ICNumber = new javax.swing.JTextField();
        textfield_username = new javax.swing.JTextField();
        textfield_email = new javax.swing.JTextField();
        textfield_contactNumber = new javax.swing.JTextField();
        button_register = new javax.swing.JButton();
        passwordField_password = new javax.swing.JPasswordField();
        button_goBack = new javax.swing.JButton();

        jdialog_registerComplete.setSize(new java.awt.Dimension(540, 400));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thank You for Registering with Us.");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please Log In To Use The System");

        button_done.setText("Done");
        button_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdialog_registerCompleteLayout = new javax.swing.GroupLayout(jdialog_registerComplete.getContentPane());
        jdialog_registerComplete.getContentPane().setLayout(jdialog_registerCompleteLayout);
        jdialog_registerCompleteLayout.setHorizontalGroup(
            jdialog_registerCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdialog_registerCompleteLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jdialog_registerCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jdialog_registerCompleteLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(button_done, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jdialog_registerCompleteLayout.setVerticalGroup(
            jdialog_registerCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdialog_registerCompleteLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(button_done)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        jPanel2.setBackground(new java.awt.Color(255, 251, 235));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));

        label_registerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_registerTitle.setText("User Registration");

        label_ICNumberTitle.setText("IC Number");

        label_userNameTitle.setText("User Name:");

        label_passwordTitle.setText("Password");

        label_emailTitle.setText("Email");

        label_contactNumberTitle.setText("Contact Number");

        button_register.setBackground(new java.awt.Color(64, 50, 184));
        button_register.setForeground(new java.awt.Color(255, 255, 255));
        button_register.setText("Register");
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });

        button_goBack.setBackground(new java.awt.Color(64, 50, 184));
        button_goBack.setForeground(new java.awt.Color(255, 255, 255));
        button_goBack.setText("Go Back");
        button_goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_goBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_goBack)
                        .addGap(18, 18, 18)
                        .addComponent(button_register))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_userNameTitle)
                            .addComponent(label_ICNumberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_passwordTitle)
                            .addComponent(label_emailTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_contactNumberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textfield_ICNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(textfield_username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(textfield_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(textfield_contactNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(passwordField_password, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_registerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(label_registerTitle)
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_ICNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ICNumberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_userNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_passwordTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_emailTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(textfield_email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_contactNumberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_register)
                    .addComponent(button_goBack))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        
        boolean registerStatus = true;
        
        String userID = textfield_ICNumber.getText();
        String userName = textfield_username.getText();
        String password = passwordField_password.getText();
        String email = textfield_email.getText();
        String contactNumber = textfield_contactNumber.getText();
        
        if(userID.length() < 12 || userID.isEmpty()){
            registerStatus = false;   
            label_registerTitle.setText("IC Number Invalid");
        }
        else if (userName.isEmpty()){
            registerStatus = false;   
            label_registerTitle.setText("User Name Cannot Be Empty");
        }
        else if(password.length() < 12 || password.isEmpty()){
            registerStatus = false;   
            label_registerTitle.setText("Password Must Be 12 Characters and Cannot Be Empty");
        }
        else if(email.isEmpty()){
            registerStatus = false;   
            label_registerTitle.setText("Email Cannot Be Empty");
        }
        else if(contactNumber.isEmpty()){
            registerStatus = false;
            label_registerTitle.setText("Contact Number Cannot Be Empty");
        }
        else if(contactNumber.length()<10 || contactNumber.length()>11){
            registerStatus = false;
            label_registerTitle.setText("Contact Number Format Is Invalid");
        }
        
        
        if(registerStatus){
            
            Users userEntity = Users.getInstance();
            userEntity.setUserID(userID);
            userEntity.setUserName(userName);
            userEntity.setPassword(password);
            userEntity.setEmail(email);
            userEntity.setContactNumber(contactNumber);
        
            try{
                Connection conDB = DriverManager.getConnection("jdbc:mysql://localhost/oecd","root","");
                Statement stmt = conDB.createStatement();

                stmt.executeUpdate("INSERT INTO users (userID, userName,password,email,contactNumber) "
                        + "VALUES ('"+userEntity.getUserID()+"','"+userEntity.getUserName()+"','"+userEntity.getPassword()+"',"
                                + "'"+userEntity.getEmail()+"','"+userEntity.getContactNumber()+"')");


            }
            catch(SQLException exception){
                System.out.println(exception);
                registerStatus = false;   
            }

            jdialog_registerComplete.pack();
            jdialog_registerComplete.setLocationRelativeTo(null);
            jdialog_registerComplete.show();
        }
    }//GEN-LAST:event_button_registerActionPerformed

    private void button_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_doneActionPerformed
        LoginUI itemloader = new LoginUI();
        itemloader.setVisible(true);
        dispose();
        jdialog_registerComplete.dispose();
    }//GEN-LAST:event_button_doneActionPerformed

    private void button_goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_goBackActionPerformed
        LoginUI itemloader = new LoginUI();
        itemloader.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_goBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegisterUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_done;
    private javax.swing.JButton button_goBack;
    private javax.swing.JButton button_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JDialog jdialog_registerComplete;
    private javax.swing.JLabel label_ICNumberTitle;
    private javax.swing.JLabel label_contactNumberTitle;
    private javax.swing.JLabel label_emailTitle;
    private javax.swing.JLabel label_passwordTitle;
    private javax.swing.JLabel label_registerTitle;
    private javax.swing.JLabel label_userNameTitle;
    private javax.swing.JPasswordField passwordField_password;
    private javax.swing.JTextField textfield_ICNumber;
    private javax.swing.JTextField textfield_contactNumber;
    private javax.swing.JTextField textfield_email;
    private javax.swing.JTextField textfield_username;
    // End of variables declaration//GEN-END:variables
}
